### PR TITLE
added new sui-pre-commit-rules & redefined some classes

### PR DESCRIPTION
**Pull request by nguasch**
I've added the new lint (sui-pre-commit-rules) dependency, script and pre-commit.
I changed too some _buttons rules

please, review: @nucliweb @PablitoGS @larnedo 

If it's Ok, I updating on the other repos

### CODE REVIEW

**Comment by nguasch** [comment]
WIP

**Comment by nguasch** [comment]
Please, review: @PablitoGS @nucliweb @larnedo

**Comment by PablitoGS** [comment]
@nguasch please fix first conflicts ;)

**Comment by nguasch** [comment]
conflicts fixed
@PablitoGS

**Comment by PablitoGS** [comment]
:+1:

**Comment by nucliweb** [comment]
:+1:

**Pull request merged**
